markdown: rdiscount
pygments: true
permalink: /:title.html
auto: true
rdiscount:
  extensions: [smart]

name: Pagoda Blog
url: http://alagu.github.io/pagoda-blog
description: News and Thoughts about Pagoda.
gravatar_url: pagoda-logo.png
